#!/usr/bin/env python3
"""Build the claude.ai skill package from claude-ai/preferences.md.

claude.ai and Cowork cannot install a Claude Code plugin, and Cowork does not
read the profile instructions field the way a normal chat does. A skill is the
one thing both surfaces accept, so the same text is packaged as a skill here.

Run this after any edit to claude-ai/preferences.md:

    python3 claude-ai/build.py

Check before a release with:

    python3 claude-ai/build.py --check

Only the Python standard library is used.
"""

import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO, "claude-ai", "preferences.md")
OUT_DIR = os.path.join(REPO, "claude-ai", "plain-precise")
OUT = os.path.join(OUT_DIR, "SKILL.md")

START = "## Copy from here"
STOP = "## Copy to here"

# The description decides whether Claude loads the skill on its own, so it names
# the kinds of output the rules apply to rather than describing the rules.
FRONTMATTER = """---
name: plain-precise
description: Writing rules for every reply, explanation, summary, analysis or document written for this user. Plain English for a non-native English reader, with every technical term kept exact. Load this before writing any prose.
---

<!--
Generated by claude-ai/build.py. Do not edit this file by hand.
Edit claude-ai/preferences.md, then run: python3 claude-ai/build.py
-->

# How to write to me

Apply these rules to every reply you write for me, and to any document you write
for me. They do not apply to code, to commit messages, or to tool calls.

"""


def read(path):
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def body(text):
    """Return the text between the two copy markers in preferences.md."""
    start = text.find(START)
    if start < 0:
        raise SystemExit("error: %s has no line reading %r" % (SOURCE, START))
    stop = text.find(STOP, start)
    if stop < 0:
        raise SystemExit("error: %s has no line reading %r" % (SOURCE, STOP))
    return text[start + len(START):stop].strip() + "\n"


def build():
    return FRONTMATTER + body(read(SOURCE))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file on disk differs from what this script would write",
    )
    args = parser.parse_args()

    built = build()

    if args.check:
        if not os.path.exists(OUT) or read(OUT) != built:
            print("claude-ai/plain-precise/SKILL.md is out of date. "
                  "Run: python3 claude-ai/build.py")
            return 1
        print("claude-ai/plain-precise/SKILL.md is up to date")
        return 0

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(built)
    print("wrote %s (about %d words)" % (OUT, len(built.split())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
