#!/usr/bin/env python3
"""Build codex/AGENTS.md from the two files that hold the rules.

Codex has one instruction file and no output-style mechanism, so the writing
rules and the research-integrity rules have to live in the same file there.
Claude Code keeps them apart, because an output style and CLAUDE.md sit at
different levels and reach different places.

Run this after any edit to the style file or to claude-md-snippet.md:

    python3 codex/build.py

Check in continuous integration, or before a release, with:

    python3 codex/build.py --check

Only the Python standard library is used.
"""

import argparse
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STYLE = os.path.join(REPO, "plugins", "plain-precise", "output-styles", "plain-precise.md")
SNIPPET = os.path.join(REPO, "claude-md-snippet.md")
OUT = os.path.join(REPO, "codex", "AGENTS.md")

HEADER = """<!--
Generated by codex/build.py. Do not edit this file by hand.
Edit plugins/plain-precise/output-styles/plain-precise.md, or
claude-md-snippet.md, and then run: python3 codex/build.py
-->

"""

NOTE = """
# Note on where these rules come from

The two sections below come from one source, the `plain-precise` rule set.
Claude Code splits them across two files, because an output style modifies the
system prompt and `CLAUDE.md` is added as a user message. Codex has one
instruction file, so both sections are here together.

"""


def read(path):
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def strip_frontmatter(text):
    """Remove a leading YAML frontmatter block delimited by --- lines.

    Codex does not read the frontmatter, so leaving it in would only show the
    reader four lines of Claude Code configuration.
    """
    lines = text.splitlines(True)
    if not lines or lines[0].strip() != "---":
        return text
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "".join(lines[index + 1:]).lstrip("\n")
    raise SystemExit("error: %s opens a frontmatter block that never closes" % STYLE)


def fenced_block(text, path):
    """Return the contents of the first ```markdown fenced block."""
    lines = text.splitlines(True)
    start = None
    for index, line in enumerate(lines):
        if line.strip() == "```markdown":
            start = index + 1
            break
    if start is None:
        raise SystemExit("error: no ```markdown block found in %s" % path)
    for index in range(start, len(lines)):
        if lines[index].strip() == "```":
            return "".join(lines[start:index])
    raise SystemExit("error: the ```markdown block in %s is never closed" % path)


def integrity_rules(text, path):
    """Return the research-integrity part of the snippet, without the short
    writing summary that precedes it.

    The short summary points the reader at the output style, and in the Codex
    file the full writing rules are already present, so the pointer would be
    wrong.
    """
    block = fenced_block(text, path)
    marker = "# Research integrity rules"
    position = block.find(marker)
    if position < 0:
        raise SystemExit("error: %s has no line reading %r" % (path, marker))
    return block[position:].rstrip() + "\n"


def build():
    style = strip_frontmatter(read(STYLE)).rstrip() + "\n"
    rules = integrity_rules(read(SNIPPET), SNIPPET)
    return HEADER + NOTE + style + "\n\n" + rules


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the file on disk differs from what this script would write",
    )
    args = parser.parse_args()

    built = build()

    if args.check:
        if not os.path.exists(OUT):
            print("codex/AGENTS.md does not exist. Run: python3 codex/build.py")
            return 1
        if read(OUT) != built:
            print("codex/AGENTS.md is out of date. Run: python3 codex/build.py")
            return 1
        print("codex/AGENTS.md is up to date")
        return 0

    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(built)
    words = len(built.split())
    print("wrote %s (%d lines, about %d words)" % (OUT, built.count("\n"), words))
    return 0


if __name__ == "__main__":
    sys.exit(main())
